### ISSUE TITLE
pages

### ISSUE THREAD

**Issue by tommydjarf** [dennan141/Grupp2_hackathon#22]
Säg till om det inte löser sig med länken så hjälps vi åt! :)

**Comment by dennan141** [comment]
Tjena!
Kom precis hem och slängde iväg den på Canvas nu! :)

Vänliga hälsningar,
Dennis

1 sep. 2023 kl. 15:12 skrev tommydjarf ***@***.***>:

﻿

Säg till om det inte löser sig med länken så hjälps vi åt! :)
